### ISSUE TITLE
Exercise 9. Move countries from one box to the other.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/javascript#9]
https://github.com/osifoanosike/javascript/tree/master/exercise9

Create two multiple selection box
First box contains list of countries and when you select a country and click on add button. Selected country will disappear from first box and appear in second button. And when you select a country from second box and click on remove button it will disappear from second box and appear in first box

**Comment by mkangia** [comment]
Osifo this seems to be working well.
Just a couple of things:
1) why using 'undefined' here : to_list.add(selected_options[i], undefined)
2) can you better naming or architecture like
AllCountryList , SelectedList, Addbutton, RemoveButton instead of lists A and B with add remove button.. 
Also reconsider 'CountryChooser' . Apt naming is really important 

Accepting this. But do consider suggestion for better coding in future

**Comment by osifoanosike** [comment]
Okay, noted. Thanks
